# Generated by Django 3.0.5 on 2020-04-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='amount_of_coolness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_coolness',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
